language: csharp
dist: trusty
mono:
- 4.0.5
addons:
  apt:
    packages:
      - make
      - gcc
      - libunwind8
      - libssl-dev
      - unzip
      - gettext
      - libcurl4-openssl-dev
      - libicu-dev
      - zlib1g
sudo: required
install:
  - curl -sSL https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.sh | sh && source ~/.dnx/dnvm/dnvm.sh && dnvm upgrade
script:
- ". ./build.sh"